### ISSUE TITLE
Sirkulasi Menggunakan Akasia template Error

### ISSUE THREAD

**Issue by prazetyo** [slims/slims9_bulian#10]
Ketika Saya memilih Akasia template untuk halaman Admin, tampilan sirkulasinya menjadi error. Screenshot bisa dilihat di bawah ini.

![image](https://user-images.githubusercontent.com/9956953/76728622-d16d4080-6789-11ea-9bd6-9dec327d8fae.png)

Terima kasih

**Comment by buitenzorg812** [comment]
pada mesin saya, tidak ada masalah, gan. 

![Lembaga Literasi Indonesia | Senayan Library Management System - Google Chrome_672](https://user-images.githubusercontent.com/125229/76731594-59564900-6790-11ea-89b9-1e8dbcaa45a0.png)

ini info lingkungan sistem pada mesin yang saya gunakan.

![Selection_673](https://user-images.githubusercontent.com/125229/76731664-89055100-6790-11ea-921e-ab11c2ff3855.png)

**Comment by prazetyo** [comment]
ini di tempat saya.
![image](https://user-images.githubusercontent.com/9956953/76738041-742eba80-679c-11ea-9db9-3e681f68ff7c.png)
Apa mngkn harus update slimsnya ke 9.1.1 ???

**Comment by prazetyo** [comment]
ini sistem di tempat saya
![image](https://user-images.githubusercontent.com/9956953/76738151-ab04d080-679c-11ea-904d-476520905bb3.png)
Apa mngkn harus update ke slims 9.1.1 ?

**Comment by prazetyo** [comment]
ini di tempat saya
![image](https://user-images.githubusercontent.com/9956953/76738227-d1c30700-679c-11ea-9619-acb5ce309563.png)
Apa harus update ke slims 9.1.1 ?

**Comment by buitenzorg812** [comment]
secara baku, slims yang kakak unduh dari slims.web.id, release-nya sudah 9.1.1. atau, kakak masih menggunakan rilis awal slims 9 bulian? di mesin saya sudah 9.1.1.

![Selection_676](https://user-images.githubusercontent.com/125229/76739669-210a3700-679f-11ea-83cd-5c6a04374c4c.png)

**Comment by prazetyo** [comment]
> 
> 
> secara baku, slims yang kakak unduh dari slims.web.id, release-nya sudah 9.1.1. atau, kakak masih menggunakan rilis awal slims 9 bulian? di mesin saya sudah 9.1.1.
> 
> ![Selection_676](https://user-images.githubusercontent.com/125229/76739669-210a3700-679f-11ea-83cd-5c6a04374c4c.png)

Iya mas...masih yg versi 9...blm yang 9.1.1. Apa sy tinggal paste saja seluruh script ke foldernya?

**Comment by buitenzorg812** [comment]
> Iya mas...masih yg versi 9...blm yang 9.1.1. Apa sy tinggal paste saja seluruh script ke foldernya?

sudah kakak pastikan bahwa kakak memang menggunakan kode dengan tag "v9"?

**Comment by prazetyo** [comment]
> 
> 
> > Iya mas...masih yg versi 9...blm yang 9.1.1. Apa sy tinggal paste saja seluruh script ke foldernya?
> 
> sudah kakak pastikan bahwa kakak memang menggunakan kode dengan tag "v9"?

![image](https://user-images.githubusercontent.com/9956953/76741222-c7efd280-67a1-11ea-9da2-ba411f2582ea.png)

**Comment by buitenzorg812** [comment]
untuk upgrade dari tag rilis v9 ke tag rilis v9.1.1, kakak unduh saja source code dari slims.web.id. kemudian lakukan seperti proses install. bedanya, pada saat muncul opsi install atau upgrade, kakak jangan pilih install. tapi pilih upgrade.

sementara itu dulu, kak. silahkan dicoba.

**Comment by prazetyo** [comment]
> 
> 
> untuk upgrade dari tag rilis v9 ke tag rilis v9.1.1, kakak unduh saja source code dari slims.web.id. kemudian lakukan seperti proses install. bedanya, pada saat muncul opsi install atau upgrade, kakak jangan pilih install. tapi pilih upgrade.
> 
> sementara itu dulu, kak. silahkan dicoba. saya harap, dengan menggunakan tag rilis v9.1.1 bisa jadi solusi masalahnya kakak.

Baik mas....siap. Saya coba dulu, nanti saya infokan lagi disini. Terima kasih

**Comment by prazetyo** [comment]
Malam mas...tadi sudah upgrade ke Slims 9.1.1 dan akhirnya masalahnya terselesaikan. Terima kasih atas bantuannya.
