### ISSUE TITLE
Pencarian buku tidak menghasilkan data yang sesuai

### ISSUE THREAD

**Issue by mimbar** [slims/slims9_bulian#112]
**Describe the bug**
Pencarian buku dengan kata kunci tertentu tidak menghasilkan data yang sesuai. Kami melakukan upgrade dari versi SLIMS 7 ke SLIMS 9.

**To Reproduce**
1. Menuju Halaman Utama
2. Masukan kata kunci
3. Enter

**Expected behavior**
Data yang dimunculkan tidak sesuai dengan kata kunci. Misalkan ada judul sbb:
`Low Vision Aids & Technology : A Guide`

Buku tersebut bisa ditemukan dengan kata kunci:
`vision` / `Vision`
`aids` / `Aids`

![image](https://user-images.githubusercontent.com/2446798/143171132-45f34bf6-b0e1-44aa-a252-c315820820dc.png)

tetapi **Tidak bisa ditemukan** dengan kata kunci:
`low`
`low vision`

![image](https://user-images.githubusercontent.com/2446798/143171072-0f3fd00f-f76c-4c23-aa53-7c705d38c36b.png)

atau bahkan tidak bisa ditemukan dengan judul lengkap

![image](https://user-images.githubusercontent.com/2446798/143171283-c0612474-59c8-4f78-b211-5e2cab2d7305.png)

Pada versi senayan 7, masih bisa ditemukan:
![image](https://user-images.githubusercontent.com/2446798/143171468-e945b608-14e6-4b57-9643-0a1d00a681a0.png)

Untuk senayan 9, tidak dapat ditemukan:
![image](https://user-images.githubusercontent.com/2446798/143171544-5150b0bf-03ff-4067-be26-e89cb93869a8.png)

**Screenshots**
Attached above.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04, MacOS Catalina, Windows 10/11
 - Browser you name it. Tried every browser.
 - Version latest on 24 Nov 2021

**Additional context**
mungkin OOT, tapi dengan pencarian ini pengunjung dapat mengetahui kami memiliki buku ini atau tidak. jadi sangat membantu dan agar menghindari kontak langsung dengan pustakawan karena kami sudah menyediakan komputer untuk pencarian judul buku.

**Comment by wynerst** [comment]
Lihat video
https://youtu.be/TZZY0hYfDnM
Atau disini
https://youtu.be/ka-UOVNW2-Q
