### ISSUE TITLE
Foto anggota tidak ditampilkan (dtampilkan hanya sebagian)

### ISSUE THREAD

**Issue by alfianhanafi** [slims/slims9_bulian#12]
**Describe the bug**
Issue terjadi setelah upgrade versi slims dari Akasia v.8.3.1 (terbaru) ke Slims 9.1.1 (bulian),
foto anggota ada yang tidak ditampilkan dan ada yang ditampilkan, di folder image/person ada semua. Saya sudah mencoba menacari solusi di internet namun tidak berhasil, tepatnya pada [tutorial ini](https://www.slimskudus.web.id/2017/01/masalah-foto-anggota-sampul-buku-tidak-Muncul-Pasca-Upgrade-PSLiMS-8.html).

**To Reproduce**
1. Masuk menu keanggotaan
2. cari daftar mahasiswa

**Expected behavior**
Muncul semua foto anggota sesuai yang anggota yang dicari

**Screenshots**
![keanggotaan akasia edited](https://user-images.githubusercontent.com/54639904/77034002-53a07380-69db-11ea-9467-6125f60c0ee8.jpg)
Di akasia muncul

![keanggotaan bulian edited](https://user-images.githubusercontent.com/54639904/77034027-6b77f780-69db-11ea-96eb-29bb5dfec26f.jpg)
di Bulian tidak muncul

![top reader bulian edited](https://user-images.githubusercontent.com/54639904/77034061-89455c80-69db-11ea-8c44-df5632510bb8.jpg)
untuk top reader juga

**Desktop (please complete the following information):**
 - OS: Win7, elementary os
 - Browser: Chrome, firefox

**Additional context**
mohon bantuannya dan Terima kasih

**Comment by desawarna** [comment]
Foto yang di SLiMS awal / SLiMS 8 sudah dicopy paste ?
ada di **/slims8/images/persons**
![Screenshot from 2020-03-21 03-29-14](https://user-images.githubusercontent.com/1111630/77203916-37f4b480-6b24-11ea-9222-878b30c2c5d7.png)
Silahkan dicopas ke **/slims8/images/persons**

**Comment by desawarna** [comment]
Itu tester **server** nya di system operasi Linux elementary os ?
Jika ya , ubah hak akses nya pakai perintah terminal 
`chmod 777 images`
FYI : Ingat tiap web server beda beda lokasi apache/nginx nya pastikan anda tahu pakai web server apa , sehingga mengetikan perintah terminal dengan tepat :clinking_glasses: 

FYI : [Tutorial yang dicoba](https://www.slimskudus.web.id/2017/01/masalah-foto-anggota-sampul-buku-tidak-Muncul-Pasca-Upgrade-PSLiMS-8.html) digunakan pada upgrade SLiMS 5 /Psenayan 5 / SLiMS 7 / PSLiMS 7 ke SLiMS 8 / PSLiMS 8.3.1 , berbeda dengan SLiMS 9.x.x karena source code tiap SLiMS ada perbedaan :smiley_cat:

**Comment by alfianhanafi** [comment]
> Foto yang di SLiMS awal / SLiMS 8 sudah dicopy paste ?
> ada di **/slims8/images/persons**
> ![Screenshot from 2020-03-21 03-29-14](https://user-images.githubusercontent.com/1111630/77203916-37f4b480-6b24-11ea-9222-878b30c2c5d7.png)
> Silahkan dicopas ke **/slims9/images/persons**

- [x] copas folder copas sudah

**Comment by alfianhanafi** [comment]
Kalau mau generate ulang thumbnail gimana ya?

mau tanya juga kenapa file profil foto di folder persons tidak semua mempunyai ekstensi jpg 

![image](https://user-images.githubusercontent.com/54639904/77217496-9d14ce00-6b55-11ea-88ea-ac2abb57214a.png)

**Comment by idoalit** [comment]
> * [x]  copas folder copas sudah
> * [x]  chmod 777 pada images, tapi masih tetep gk muncul
> * [x]  chmod 777 recursive semua folder dan file didalam folder images tetep gk bisa
> 
> ![image](https://user-images.githubusercontent.com/54639904/77216866-71431980-6b50-11ea-8f76-bda1d35d5565.png)
> 
> setelah saya lihat-lihat ternyata, dari folder/person yang Akasia ternyata thumbnail muncul semua sedangkan yang di slims 9(bulian) ada yang muncul ada yang tidak.
> 
> **Bulian**
> ![person bulian edited](https://user-images.githubusercontent.com/54639904/77217265-c9c7e600-6b53-11ea-9bcc-e1afa8c115cf.jpg)
> 
> **Akasia**
> ![person akasia edited](https://user-images.githubusercontent.com/54639904/77217279-d3514e00-6b53-11ea-979e-82c307536a4a.jpg)
> 
> Jadi kayaknya masalah di thumbnail yang di bulian
> saya kurang tau apa yang menjadikannya seperti itu, padahal itu saya copas dari folder akasia ke folder personnya bulian
> saya pake localhost xammp
> terima kasih responnya mas Zae Makhrus, tutorial anda yang lain sangat membantu.

Bukan masalah thumbnail di explorer/file manager seperti yg tertampil. Itu tidak ada hubungannya dengan SLiMS. Jika memang filenya ada, pastikan dapat diakses. 
Sebagai contoh:
- Misalkan alamat SLiMSnya adalah http://localhost/slims
- Maka, coba akses langsung imagenya seperti berikut: `http://localhost/slims/images/persons/<nama file>` => http://localhost/slims/images/persons/member_2007141001E810.jpg
- Jika tidak muncul gambarnya di browser, maka kemungkinan masalah di permission.
- Sepemahaman saya, jika anda menggunakan xampp, anda membutuhkan akses root untuk merubah permission. Gunakan terminal untuk melakukannya.
```
$ sudo chmod -R 777 /opt/xampp/htdocs/slims/images
```

**Comment by alfianhanafi** [comment]
- [x] akses langsung images dan muncul dibrowser 
- [x] permission udah 777 semua sampe daleman

namun tetep gk muncul di bulian

**Comment by idoalit** [comment]
> * [x]  akses langsung images dan muncul dibrowser
> * [x]  permission udah 777 semua sampe daleman
> 
> namun tetep gk muncul di bulian

coba lakukan inspect element, cek seperti apa URL image yg tergenerate. Pastikan path filename sesuai.
<img width="690" alt="Screen Shot 2020-03-23 at 23 48 18" src="https://user-images.githubusercontent.com/1549628/77341210-fa309f80-6d60-11ea-831b-d4d60c298610.png">

**Comment by alfianhanafi** [comment]
Karena di Akasia tidak ada top reader jadi saya inspek di keanggotaan

**AKASIA**
meskipun tidak ada extensi jpg bisa muncul
![inspect image akasia](https://user-images.githubusercontent.com/54639904/77387056-eb78d580-6dbe-11ea-9e78-f1f14309f11f.jpg)

**Bulian**
harus reupload baru bisa muncul
![inspect image bulian](https://user-images.githubusercontent.com/54639904/77387287-97222580-6dbf-11ea-940a-22437ee6b45a.jpg)

**Comment by idoalit** [comment]
Sudah fix ya?
