### ISSUE TITLE
update from older version user login bug

### ISSUE THREAD

**Issue by nalamapu** [slims/slims9_bulian#13]
SLiMS 9 user table `passwd` filed type is varchar(64). Earlier it was 32. While upgrading (I tested it from SLiMS 7), it doesn't change to 64 rather remain 32.
As a result, none can login.

**Comment by buitenzorg812** [comment]
i also have met the same matter when upgrading from SLiMS 7 Cendana to SLiMS 9 Bulian. But on the other hand, when i use Linux server, i use linux on my laptop, there is no trouble like this, even when doing upgrade from Senayan3-Stable15, for example. The transitions were smooth. We stil need to finds out what is happening.

**Comment by awriel** [comment]
Fast solutions: 
Edit manual on MySQL / phpMyAdmin / Adminer: 
Change user table : field `passwd` from 32 to 64

**Comment by heroesoebekti** [comment]
re-create the `input_date` field on table `user`, because before cendana version `input_date` used default value `0000-00-00` and this can't accept in newest mysql and cause failed to update data
