### ISSUE TITLE
How to change Rp symbol 

### ISSUE THREAD

**Issue by sirnaiep** [slims/slims9_bulian#130]
Hi, want to know how to change Rp symbol in fine reports page ?

**Comment by anasdwc** [comment]
You can check on folder `admin -> modules -> reporting -> customs -> member_fines_list.php`

You can search Rp in there. So you can change like what you want.

**Comment by anasdwc** [comment]
> Hi, want to know how to change Rp symbol in fine reports page ?

Hi, @sirnaiep 
You can check on folder `admin -> modules -> reporting -> customs -> member_fines_list.php`
You can search Rp in there. So you can change like what you want.

**Comment by drajathasan** [comment]
Already available in SLiMS 9.5.x
https://github.com/slims/slims9_bulian/commit/eb5784a4cc983469a6b9388f48c579fe0d6f2137
