### ISSUE TITLE
Improve Searching

### ISSUE THREAD

**Issue by Faheemakbar** [slims/slims9_bulian#134]
Hi, 
    Slims 8 was good in searching while Sims9 search not good. It fails to search keywords which are available in Title or others field.  similarly it display irrelevant results in OPAC

**Comment by idoalit** [comment]
Just change your index type to "default" in your local config file if you want the results like as slims 8.

https://github.com/slims/slims9_bulian/blob/master/config/sysconfig.local.inc-sample.php#L40

**Comment by Faheemakbar** [comment]
Thanks it worked
