### ISSUE TITLE
The save button is not responding

### ISSUE THREAD

**Issue by chamidusam** [slims/slims9_bulian#137]
When I create system users, the save button is not responding. the screenshot is attached,
![slims error](https://user-images.githubusercontent.com/101945218/159133068-b45f37a9-9e3c-49a7-9358-6ee05f9cc983.JPG)

**Comment by buitenzorg812** [comment]
![image](https://user-images.githubusercontent.com/125229/159206739-04b6f345-bd6d-463a-9cf0-8a227c559dbe.png)
it's fine in my local machine. try to disable mod_security setting within your hosting.

**Comment by chamidusam** [comment]
Dear Arif Syamsudin

Thank you very much for your prompt help. It is working fine after
disabling the mod_securty. Almost a week I was stuck in this error .
Thanks again for your kind help.

best regards!

Chamidu .

**Comment by buitenzorg812** [comment]
You are welcome.

Well, the mod_sec is there absolutely for a reason. If your account has the ability to modify rules for mod_sec, try to modifying it first. Or if your ISP have the flexibility to change the rules for the mod_sec, please consult with them to make mod_sec less strict for SLiMS. I guess, turning it off is the last option.
