### ISSUE TITLE
Generate Accession Registrar

### ISSUE THREAD

**Issue by nalamapu** [slims/slims9_bulian#14]
Generating Accession Register would be a great help for those who wants a physical printed backup. The fields would be: Date, Title, Author(s), Edition, ISBN, Place, Publisher, Year, Collation, Price, Supplier and call no. 

The output can be exported as horizontal A4/Legal Size in pdf and html.

**Comment by buitenzorg812** [comment]
Thank you for your input, Alam. Some SLiMS users have made that kind of reporting for SLiMS 8 Akasia. Idk if someone, later on will be making that custom reporting for SLiMS 9 Bulian :).
