### ISSUE TITLE
Suggetion for Good Search and Retrive 

### ISSUE THREAD

**Issue by S10hivam** [slims/slims9_bulian#143]
Please USE this for Search and Retrive Date 

https://github.com/elastic/elasticsearch

**Comment by drajathasan** [comment]
Thanks for your suggestion.

SLiMS is compatible with Elasticsearch. For your information, to make SLiMS work with Elastic Search requires more resources and is not cheap for library institutions in general (only certain institutions), this is the reason why the developer not fully include Elasticsearch library in SLiMS.
