### ISSUE TITLE
Bulian9 Portable: showing following error how to solve it: All GMD/Media

### ISSUE THREAD

**Issue by Aijaz18** [slims/slims9_bulian#157]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by drajathasan** [comment]
Maybe your database is corrupted or incompatible with SLiMS code. Also you haven't give more information like your SLiMS version, OS version, browser version etc. We can't help you if you just report an issue with title only.
