### ISSUE TITLE
The default Persian language is not complete!!!

### ISSUE THREAD

**Issue by elhamifatemeh** [slims/slims9_bulian#159]
**Describe the bug**
I want to change the language to Persian, but when I change the default language to Persian from the system tab, only some titles are translated to Persian.
What should I do to solve this problem?

**Screenshots**
![Senayan](https://user-images.githubusercontent.com/90859044/186692634-8796d2f1-688f-4da8-b576-56778bed2c60.png)

**Comment by drajathasan** [comment]
Fork this repo with develop branch and make a pull request of your language translatetation at https://github.com/slims/slims9_bulian/tree/master/lib/lang/locale/fa_IR/LC_MESSAGES

edit .po files with PoEdit.

Thanks.
