### ISSUE TITLE
Quotes tidak menampil dengan sempurna

### ISSUE THREAD

**Issue by fahmiyufrizal** [slims/slims9_bulian#164]
Ditemukan quotes dengan tampilan yang tidak sempurna di laman visitor (kemungkinan di kesalahan penulisan)
![Screenshot (1)](https://user-images.githubusercontent.com/60032856/199649900-2788a942-e9e7-4bd0-b350-bfecc1ba046b.png)

**Comment by drajathasan** [comment]
itu bukan **BUG**.
SLiMS berapa?

Betul quote dari fiersa besari ada karakter aneh
![image](https://user-images.githubusercontent.com/38057222/199849793-102856b5-2e06-432a-827d-5ea8c959d708.png)

Namun, jika di refresh lagi maka quote yang lain tidak seperti itu.

![image](https://user-images.githubusercontent.com/38057222/199849942-80590c23-94c8-4bef-9c55-f4cbd4d9b0ff.png)

Tapi menurut saya label yang anda berikan **"Bug"** tidak tepat 😃. FYI, quotes diatas diambail dari https://kutipan.herokuapp.com/, silahkan kontak pengelola nya (jika ada) 😅 jika anda tidak suka ada karakter aneh.

**Comment by fahmiyufrizal** [comment]
ahh iya, bukan masuk ke bug sih ini harusnya
Ini memakai slims 9.5.0 (karena di slims 9.4.2 masih mengarah ke api.quoteable.io). Jika penyedianya adalah pihak slims sendiri, berarti bisa diperbaiki oleh pihak SLiMS.

**Comment by drajathasan** [comment]
Itu terjadi karena karakter petik satu atau petik dua yang diencode oleh browser atau komponen lain. Sehingga jika dilihat oleh manusia jadi "aneh". Akan difilter pada rilis berikut nya.

# Status solved
![image](https://user-images.githubusercontent.com/38057222/201450856-8cfcb096-4b0b-438b-b4aa-d789588f8eab.png)
Penjelasan gambar 
1. Quote sudah terfilter dari karakter html_entities
2. Karakter asli quote

# Solusi
 Jika anda ingin ini diselesaikan segera mungkin dan anda seorang programmer atau bisa memprogram, silahkan ikuti langkah dibawah berikut:

1.  Download library "he" dari [https://www.npmjs.com/package/he](https://www.npmjs.com/package/he), gunakan NPM atau apapun caranya, silahkan baca dokumentasinya dengan baik.
2. jika sudah terdownload, silahkan pindahkan file he.js ke folder js/ pada direktori SLiMS anda.
3. Silahkan modifikasi file visitor_template.php pada folder template/default/ atau folder template anda yang mungkin sudah dimodifikasi sesuai dengan gambar berikut:
![image](https://user-images.githubusercontent.com/38057222/201450989-cc89ed22-1c61-4810-8623-72e2b5ae8e64.png)

Penjelasan Gambar: 
1. file he.js di letakan dibawah axios
2. meng-overwrite isi dari res.data.content

Semoga membantu. saya close issue ini.
