### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by telyon** [slims/slims9_bulian#167]
In the page http://localhost/library/install/index.php while doing a _first-time installation_ of SLiMS version 9.5.0, I found this error:

`You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json NULL, ``r`` int(1) NOT NULL default '0', ``w`` int(1) NOT NULL default '0',' at line 4
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json NULL, ``path`` text COLLATE utf8mb4_unicode_ci NOT NULL, ``created_at`` dat' at line 3
Table 'wabioeth_library.group_access' doesn't exist`

**### Server details:**

- Apache/2.4.38 (Win64) OpenSSL/1.1.1b PHP/8.1.10
- Database client version: libmysql - mysqlnd 8.1.10

database engine `Server version: 10.1.38-MariaDB`

**Comment by idoalit** [comment]
You need `MySQL version 5.7` and or `MariaDB version 10.3` to install SLiMS 9.5

**Comment by telyon** [comment]
Hello,
I have upgraded my server to 
`Server version: 10.4.25-MariaDB` and `Database client version: libmysql - mysqlnd 8.1.10.`
Now the installation completes but I get a 500 error when I click on the "Go to my SLiMS" button (see screenshot). 
What more do I need to do?
![image](https://user-images.githubusercontent.com/54590307/200867258-bbb4ec08-b852-4ef6-bbee-f83125a79dca.png)

**Comment by idoalit** [comment]
Firstly, please open config/sysconf.env.inc.php.
And then change environment from production to development. Save it, open your SLiMS again to see the error message.

**Comment by telyon** [comment]
Here is the error:

`Fatal error: Uncaught TypeError: mysqli::__construct(): Argument #5 ($port) must be of type ?int, string given in C:\xampp\htdocs\library\sysconfig.inc.php:609 Stack trace: #0 C:\xampp\htdocs\library\sysconfig.inc.php(609): mysqli->__construct('', '', '', '', '') #1 C:\xampp\htdocs\library\index.php(30): require('C:\\xampp\\htdocs...') #2 {main} thrown in C:\xampp\htdocs\library\sysconfig.inc.php on line 609`

I have fixed the dB connection parameters and it's working fine now.
Thanks.
