### ISSUE TITLE
Halaman index.php?p=visitor tidak dapat dibuka

### ISSUE THREAD

**Issue by lexxa-tech** [slims/slims9_bulian#174]
ketika membuka halaman [example.com//index.php?p=libinfo](http://example.com/slims9/index.php?p=visitor) maka akan redirect ke halaman http://example.com/slims9/index.php

Di local bisa, namun ketika di deploy ke server tidak bisa

**Comment by drajathasan** [comment]
Apakah slims diakses dari non http://localhost? jika iya, masuk menu sistem, ubah pengaturan yang saya beri garis ungu dan ganti nilainya menjadi dari "Dimungkinkan" menjadi "tidak mungkin".

![gambar](https://user-images.githubusercontent.com/38057222/209110397-d14d7d6b-0d79-44d7-bf0c-c5ba636ed167.png)
