### ISSUE TITLE
Parse error: syntax error, unexpected '['.../slims/sysconfig.inc.php on line 465

### ISSUE THREAD

**Issue by ocavidal** [slims/slims9_bulian#18]
hi there, 

i installed slims in siteground via softaculous, installation was successful but opening it got this error

Parse error: syntax error, unexpected '[' in /home/mvcolleg/public_html/main/slims/sysconfig.inc.php on line 465.

what could be the problem?

thanks,
ocavid

**Comment by idoalit** [comment]
what version of php is used?

**Comment by idoalit** [comment]
Feel free to open this issue again if still accrued.
