### ISSUE TITLE
spreadsheet.php

### ISSUE THREAD

**Issue by elkhair** [slims/slims9_bulian#180]
spreadsheet.php on visitor report is not working

![spreadsheet](https://user-images.githubusercontent.com/53245010/214200988-cda6377e-25c7-4e81-935a-090511c65c17.jpg)
![spreadsheet2](https://user-images.githubusercontent.com/53245010/214201010-ffdb7797-f97d-4fe4-aff7-926590cd7ec8.jpg)

**Comment by drajathasan** [comment]
HI, if you still running Bulian <= 9.4.2, please follow this instrauction at this video [https://www.youtube.com/watch?v=iC99laQ7XQ4&t=240s](https://www.youtube.com/watch?v=iC99laQ7XQ4&t=240s&fbclid=IwAR3v0bx_9rh22YPQSBp2NHmhJJSJ93nR0yo1g9Wp7zhwhvgpQG2etdIdhWE)

Or if you running Bulian >= 9.5.0 follow this instruction :
1. Open system module
2. Click on System Environment Settings
3. Change "production" to "Development" then save
4. Open your problem menu, and you will see the error.

![image](https://user-images.githubusercontent.com/38057222/214870459-20aa3311-599e-40de-9973-b542f7ddb00f.png)
