### ISSUE TITLE
Tombol Simpan Pengaturan pada Halaman Pengaturan Sistem Tidak Bekerja

### ISSUE THREAD

**Issue by nolbyte** [slims/slims9_bulian#184]
Ketika tombol Simpan Pengaturan pada halaman Pengaturan Sistem ditekan, tidak terjadi apa-apa dan tidak menyimpan seperti pada halaman lain.

[![senayan.png](https://i.postimg.cc/HxkTVwdX/senayan.png)](https://postimg.cc/xkhwZbk1)

Terima kasih

**Comment by drajathasan** [comment]
Silahkan diganti menjadi tempat default, lalu coba tekan tombol simpan kembali. Jangan lupa untuk mengaktifkan mode pengembangan. Saya tidak menemukan galat apapun. Posisi saya menggunakan SLiMS 9.5.2, jika versi anda kuerang dari 9.5.2 segera upgrade ke versi terkini, dan saya tidak menumakan galat apapun. Maka label bug akan saya ganti menjadi label yang lain.


https://user-images.githubusercontent.com/38057222/224494504-2c01e0ce-d570-462e-8934-a9c626d06d70.mp4

**Comment by billalxcode** [comment]
Hi, tolong berikan penjelasan yang lebih detail lagi dari kesalahaan tersebut. Misal nya url saat error.

Sedikit ku jelaskan, bahwa web tidak dapat meload library yang bernama jquery. Jquery biasanya mendeklarasikan $ sebagai default variable. Di situ tersebut bahwa variabel $ tidak didefinisikan/deklarasikan. Menurut asumsi saya, jquery nya tidak dapat diload atau memang belum dimasukan.

Solusi nya silahkan update versi aplikasi ke versi yang terbaru, jika masih error silahkan konfirmasi ulang.

Terima kasih

**Comment by nolbyte** [comment]
Terima kasih bantuannya
Sudah teratasi dengan mengganti tema default.
