### ISSUE TITLE
XSS Injection

### ISSUE THREAD

**Issue by harrishariadi** [slims/slims9_bulian#185]
**Ketemu celah potensi injection (melalui XSS) dengan kode:**
`/index.php/'"--><script>alert('gembel')</script></index.php?p=profil-singkat`

Hasilnya adalah pop-up alert. Silakan diperiksa.

**Comment by drajathasan** [comment]
Terimakasih untuk partisipasinya. Bisa cek di 
https://github.com/slims/slims9_bulian/commit/8a8f92bfb89f383c4f2a7c1ee0077282dc981036
