### ISSUE TITLE
Gagal Instalasi Akhir Ketika Setting Admin dan Password

### ISSUE THREAD

**Issue by HepHopian** [slims/slims9_bulian#187]
hai, adakah yang memiliki masalah yang sama dan tahu solusinyaa kah?
saya ketika instal proses checking awal semuanya ceklis dan tidak ada masalah
tapi ketika finishing akhir memasukan user admin dan password muncul notif seperti ini :
TRIGGER command denied to user 'perpus4'@'10.3.33.11' for table 'loan'
TRIGGER command denied to user 'perpus4'@'10.3.33.11' for table 'loan'
TRIGGER command denied to user 'perpus4'@'10.3.33.11' for table 'loan'
sebanyak tiga baris.
![ask4](https://github.com/slims/slims9_bulian/assets/133189341/352e0f56-1e74-4a2e-b03a-3460caa77009)

**Comment by drajathasan** [comment]
Pengguna database yang anda gunakan (perpus4) tidak memiliki perijinan untuk menjalan perintah TRIGGER. Segera hubungi database administrator untuk mengubahnya.

**Comment by HepHopian** [comment]
Baik terima kasih pak drajathasan... proses instalasi sudah berhasil... tapi saya menemukan kendala lagi tidak bisa login sebagai admin kenapa ya pak? ada tulisan You are not authorized to view this section, mohon solusinya pak....
