### ISSUE TITLE
groups is reserved keyword in MySQL 8

### ISSUE THREAD

**Issue by maulinho13** [slims/slims9_bulian#19]
During fresh install of slims 9, I got error message saying: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups ...". After googling i found 'groups' is reserved keyword now for MySQL 8. Please fix this.

Also in install.sql.php and senayan.sql, insert into statement for table user insert fixed values of 'admin' with hashed password '$2y$10$pG0dqMrd2r39zRTSFSyp8.Z7sMy4cY7s/18UDQsV50Vn0TnR6UORm'? No wonder I can't log in whatever username and password I entered in the box.

**Comment by idoalit** [comment]
Please use our issue template for better bug report. Don't forget to attach screenshoot and detail error message. So we can analyze easily
