### ISSUE TITLE
SLiMs 9.6.0 Download Counter display "Uknown error"

### ISSUE THREAD

**Issue by superthin** [slims/slims9_bulian#193]
**Describe the bug**
When access page Download Counter in Admin Dashboard => Reporting => Download Counter

(file /admin/modules/reporting/customs/dl_counter.php)

it shows "Uknown error". 

I try to check PHP error logs but no information.

How can I debug this?

**Comment by superthin** [comment]
Sorry. I found the problem:

![Uploading 2023-06-23-17-35.png…]()

**Comment by adojrable** [comment]
Hallo bro @drajathasan 
I got similar trouble/bug after upgrade SLIMS to 9.6.1, the visitor counter doesn't seem work. 
![Error 500 Counter Slims](https://github.com/slims/slims9_bulian/assets/41410908/513dda11-6d61-401f-97ca-ac380c27d9ea)

**Comment by drajathasan** [comment]
> Hallo bro @drajathasan 
> I got similar trouble/bug after upgrade SLIMS to 9.6.1, the visitor counter doesn't seem work. 
> ![Error 500 Counter Slims](https://github.com/slims/slims9_bulian/assets/41410908/513dda11-6d61-401f-97ca-ac380c27d9ea)
> 

GO to module system, click on "System Environment Setting" change Production to Development then save. Back to the last menu, and you will get an error message, screenshot it into this comment.
