### ISSUE TITLE
Quality of books on home page (default theme) cannot change?

### ISSUE THREAD

**Issue by superthin** [slims/slims9_bulian#196]
**Describe the bug**
Change template/default/tinfo.inc.php to display many books instead of 6 default.

```
$sysconf['template']['classic_popular_collection'] = 1;
$sysconf['template']['classic_popular_collection_item'] = 6; // change to 12 doesn't work
$sysconf['template']['classic_new_collection'] = 1;
$sysconf['template']['classic_new_collection_item'] = 6; // change to 12 doesn't work
```
I cannot change the quantity of books in home page. Theme Default.

How can I change this behaviour?

**Comment by lau01402** [comment]
I think what i found is the one you ask for . 
by using (default theme) 

New collections + updated 

api\v1\controllers\BiblioController.php
line:74		$limit = 6;     // change here , to allow  [ New collections + updated ] , show more.

**Comment by superthin** [comment]
Thank @lau01402  so much! You saved my day.
