### ISSUE TITLE
Bibliography Module: Publisher, Publishing Place, and Classification can't be filled.

### ISSUE THREAD

**Issue by stephen18961** [slims/slims9_bulian#203]
**Describe the bug**
The bug exists on the "Bibliography" module on the admin page. Any fields other than "Publisher", "Publishing Place", and "Classification" can be filled with text. But these 3 mentioned columns cannot be filled, as they pop up and search for an entry from the master file. These columns will keep searching, therefore no data can be inserted. There are screenshots down below, after the steps to reproduce.
(This issue happens on a hosted site)

**To Reproduce**
1. Go to Bibliography (admin)
2. Click on Add new Bibliography
3. Scroll down to "Publisher" (to fill data)

**Expected behavior**
These boxes should show the available names from master file, or show the option to add the name if the typed name doesn't exist.

**Screenshots**
This is how it looks like:
![image](https://github.com/slims/slims9_bulian/assets/92841816/0e3dba56-1040-4861-a780-1a8aa6e66294)
The keyword "Calvin" exists in the master file, therefore it should have been like this:
![image](https://github.com/slims/slims9_bulian/assets/92841816/8f0d1cf6-5c91-49b0-bfeb-0dc7c770f36e)
(The expected image is tested from another hosting site, but the hosting site used where the bugs exist, other people there who use slims don't have this issue).

**Desktop (please complete the following information):**
 - OS: Linux isv02-sh-salak.idcloudhosting.com 3.10.0-962.3.2.lve1.5.76.el7.x86_64
 - Browser: Tested with Firefox and Chrome
 - Version Slims v.9.6.1

**Additional context**

**Comment by drajathasan** [comment]
It because your server block SLiMS http request via AJAX by ModSec. The solution is disable your ModSec (If you want this feature work)
