### ISSUE TITLE
How to inspect code to find the issue of login?

### ISSUE THREAD

**Issue by superthin** [slims/slims9_bulian#215]
**Describe**
Some time when you login member account and after that login staff account, it make member account logged out.

**To Reproduce**
1. Login with a member account in a tab or browser (tab 1)
2. Open in new tab and login with an staff or super admin user
3. Switch to tab 1 with user account login to seach, to view profile,...
4. User account lost session and logged out

It's not always to occur like above so I don't know why. The problem in many environment: XAMPP localhost, on hosting with CentOS, Ubuntu, PHP 7.4, 8.1, 8.2.

**Comment by drajathasan** [comment]
Its default behavior of SLIMS because Cookie of Member Area is not same with Admin area. If you want to login at same time (Admin and Member), First you must login into admin, then you login to member area.

**Comment by linuxguist** [comment]
Alternately, you can use multiple internet browsers ( eg. Firefox , Google Chrome etc. ), to login with member & staff account, parallely, on the same computer.
