### ISSUE TITLE
admin_template all

### ISSUE THREAD

**Issue by adhity4** [slims/slims9_bulian#22]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**pencarian pada item barcode
ketika mencari kode barcode hasilnya 0 padahal data item tersebut mau kita cetak barcodenya

**Comment by idoalit** [comment]
Please, use template to describe your issue.
