### ISSUE TITLE
The author's name in bibliographi increases automatically

### ISSUE THREAD

**Issue by Anry08** [slims/slims9_bulian#224]
I have problems. when I input books data into the slims bibliography section. Then I save the data. The author's name in bibliographi increases automatically. for example, I will enter data for book "A" which has one author when I save and I see list in bibliographi. The book "A" become two authors. So, how to solve this problem?

Information :
- Slims version 9 Bulian 9.42
- Xampp control v3.2.4
- Operating System Windows 10 64 bit
- Browser Google Chrome, Mozilla Firefox

**Comment by drajathasan** [comment]
Coba untuk upgrade ke versi terbaru. Karena SLiMS 9.4.2 versi lawas.
