### ISSUE TITLE
 Peringatan  Tidak tersedia interaksi dengan modul ini. Hubungi administrator sistem untuk mengatur akses yang diperlukan.

### ISSUE THREAD

**Issue by inaifas** [slims/slims9_bulian#228]
Bagaimana mengatasi masalah semua user selain super admin tidak dapat mengakses sirkulasi(padahal pada menu hak akses telah diberikan pada modul ini) dengan informasi kegagalan seperti dibawah ini

Peringatan
Tidak tersedia interaksi dengan modul ini. Hubungi administrator sistem untuk mengatur akses yang diperlukan.

**Comment by drajathasan** [comment]
Selain akses, juga harus ditentukan juga akses nya menu nya seperti pada gambar.
![image](https://github.com/slims/slims9_bulian/assets/38057222/294dfa08-67e4-4029-a70c-69e07b970c20)

**Comment by siberakunesia** [comment]
terima kasih, mas. ternyata saya kutil, kumat.

**Comment by goeng1** [comment]
cara created super ussernya bagaimana kak, saya baru update db dari slims 9.2.2 ke 9.7.2 sehingga akun yang ada tidak bisa mengakses super user, bagaimana cara menambahkan nya ?

**Comment by Ozgurujim** [comment]
> cara created super ussernya bagaimana kak, saya baru update db dari slims 9.2.2 ke 9.7.2 sehingga akun yang ada tidak bisa mengakses super user, bagaimana cara menambahkan nya ?

I believe in 9.7.2 there can only be one "super-user" with user id = 1 , that has access to all system functions. Usually this user has username = admin . If you have lost the username/password for that user, you will need to reset it.
