### ISSUE TITLE
Database relation & Unresponsive admin page

### ISSUE THREAD

**Issue by 0x4164** [slims/slims9_bulian#23]
**Issue**
1. Database relation
I see no connection to certain supposed tables. This might lead to desynchronized data.
![image](https://user-images.githubusercontent.com/24596057/84590362-fdb75c80-ae5f-11ea-8c8b-ef1490b8aeca.png)

2. Unresponsive page
Sometime we have conditions to access admin page from mobile browser. It is very uncomfortable to see such UI.

**admin**
![image](https://user-images.githubusercontent.com/24596057/84590243-08bdbd00-ae5f-11ea-8cfc-53aab490ce31.png)
![image](https://user-images.githubusercontent.com/24596057/84590298-8eda0380-ae5f-11ea-8b4a-caed7aacb2c4.png)

**home**
![image](https://user-images.githubusercontent.com/24596057/84590728-3573d380-ae63-11ea-9639-841a33e9f254.png)

**Expectation**
I hope someone ( or me, if i have time ) will fix this soon.

**Comment by idoalit** [comment]
1. It's not issue. SLiMS stile use myisam, so database relation not showing.
2. Yep, admin page currently just for desktop mode.

and I hope to.
