### ISSUE TITLE
Pembayaran Denda

### ISSUE THREAD

**Issue by vathunt** [slims/slims9_bulian#230]
Untuk update SLiMS 9 ini ketika ada denda dan pemustaka membayar denda tersebut, pada menu Pelaporan Denda tidak terhitung pada tanggal pemustaka membayar denda tersebut akan tetapi akan tercatat pada tanggal denda tersebut disimpan.

Mohon petunjuknya, terima kasih.

**Comment by drajathasan** [comment]
Alasan mengapa tidak langsung tersimpan karena denda itu pada umumnya dilapangan sangat lah bervariatif perihal kejadiannya. 

Misal contoh kasus nya yaitu Denda yang terlalu besar untuk dibayar, apakah langsung dibayarkan? kan bisa jadi ceritanya "Pak saya cuma bawa sekian rupiah bagaimana ya? ini saya kembalikan dulu, saya kurang nya berapa ya?" dengan ini pustakawan bisa langsung mengembalikan buku itu lalu masuk tab denda untuk mengedit denda anak tersebut mau bayar berapa dulu dengan kata lain masih punya tanggungan.

atau bisa jadi ceritanya "Pak, ini denda saya kan 1 juta, padahal saya harus wisuda tahun ini atau saya akan di DO, apa gak ada keringanan?" kalau sudah 1juta mau diedit apanya? tanggal kembalinya dirubah? kan cape harus masuk database hehehe, maka solusinya sama seperti cerita sebelunbya, kembalikan itu buku -> masuk tab denda -> lalu edit denda yang 1 juta itu dengan "diskon" yang diputuskan agar memperingan Ybs.

Jadi jangan lupa update data denda nya sebelum klik "Selesai Transaksi" ya 😉

**Comment by arifcahyob** [comment]
![Denda](https://github.com/user-attachments/assets/88172e14-a38e-4b44-b8a9-300a55e0277e)

Kasus seperti ini apakah bug?
dalam 1 transaksi ada buku yang kena denda dan tidak.

**Comment by drajathasan** [comment]
> ![Denda](https://private-user-images.githubusercontent.com/21982249/374846540-88172e14-a38e-4b44-b8a9-300a55e0277e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjIxNDYsIm5iZiI6MTcyODQ2MTg0NiwicGF0aCI6Ii8yMTk4MjI0OS8zNzQ4NDY1NDAtODgxNzJlMTQtYTM4ZS00YjQ0LWI4YTktMzAwYTU1ZTAyNzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA4MTcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NzJiNTliM2EzOWFkZWI0MDZjNmQyY2FmYjhiYjEzNTAxODM4YjliOGJkZDczMjIwMjdhZDk3NTE1M2UwMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3-HoOwW6HTfXApQa_MySd-0YELkuKHjShD59gYmvneo)
> 
> Kasus seperti ini apakah bug? dalam 1 transaksi ada buku yang kena denda dan tidak.

Bukan, tergantung pengaturan denda nya bagaimana. Karena denda di SLiMS bisa diatur berdasarkan banyak variabel seperti gmd, tiipe koleksi dll.

**Comment by arifcahyob** [comment]
Baik terimakasih akan kami coba cek lagi, karena kedua buku tersebut datanya sama persis, gmdnya, tipenya, dll sama..

**Comment by arifcahyob** [comment]
> > ![Denda](https://private-user-images.githubusercontent.com/21982249/374846540-88172e14-a38e-4b44-b8a9-300a55e0277e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjIxNDYsIm5iZiI6MTcyODQ2MTg0NiwicGF0aCI6Ii8yMTk4MjI0OS8zNzQ4NDY1NDAtODgxNzJlMTQtYTM4ZS00YjQ0LWI4YTktMzAwYTU1ZTAyNzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA4MTcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NzJiNTliM2EzOWFkZWI0MDZjNmQyY2FmYjhiYjEzNTAxODM4YjliOGJkZDczMjIwMjdhZDk3NTE1M2UwMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3-HoOwW6HTfXApQa_MySd-0YELkuKHjShD59gYmvneo)
> > Kasus seperti ini apakah bug? dalam 1 transaksi ada buku yang kena denda dan tidak.
> 
> Bukan, tergantung pengaturan denda nya bagaimana. Karena denda di SLiMS bisa diatur berdasarkan banyak variabel seperti gmd, tiipe koleksi dll.

mengatur variabel tersebut apakah harus modifikasi di script?

**Comment by drajathasan** [comment]
> > > ![Denda](https://private-user-images.githubusercontent.com/21982249/374846540-88172e14-a38e-4b44-b8a9-300a55e0277e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjIxNDYsIm5iZiI6MTcyODQ2MTg0NiwicGF0aCI6Ii8yMTk4MjI0OS8zNzQ4NDY1NDAtODgxNzJlMTQtYTM4ZS00YjQ0LWI4YTktMzAwYTU1ZTAyNzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA4MTcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NzJiNTliM2EzOWFkZWI0MDZjNmQyY2FmYjhiYjEzNTAxODM4YjliOGJkZDczMjIwMjdhZDk3NTE1M2UwMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3-HoOwW6HTfXApQa_MySd-0YELkuKHjShD59gYmvneo)
> > > Kasus seperti ini apakah bug? dalam 1 transaksi ada buku yang kena denda dan tidak.
> > 
> > 
> > Bukan, tergantung pengaturan denda nya bagaimana. Karena denda di SLiMS bisa diatur berdasarkan banyak variabel seperti gmd, tiipe koleksi dll.
> 
> mengatur variabel tersebut apakah harus modifikasi di script? Atau yang di bagian loan rules?

Loan rules.

**Comment by vathunt** [comment]
> Alasan mengapa tidak langsung tersimpan karena denda itu pada umumnya dilapangan sangat lah bervariatif perihal kejadiannya.
> 
> Misal contoh kasus nya yaitu Denda yang terlalu besar untuk dibayar, apakah langsung dibayarkan? kan bisa jadi ceritanya "Pak saya cuma bawa sekian rupiah bagaimana ya? ini saya kembalikan dulu, saya kurang nya berapa ya?" dengan ini pustakawan bisa langsung mengembalikan buku itu lalu masuk tab denda untuk mengedit denda anak tersebut mau bayar berapa dulu dengan kata lain masih punya tanggungan.
> 
> atau bisa jadi ceritanya "Pak, ini denda saya kan 1 juta, padahal saya harus wisuda tahun ini atau saya akan di DO, apa gak ada keringanan?" kalau sudah 1juta mau diedit apanya? tanggal kembalinya dirubah? kan cape harus masuk database hehehe, maka solusinya sama seperti cerita sebelunbya, kembalikan itu buku -> masuk tab denda -> lalu edit denda yang 1 juta itu dengan "diskon" yang diputuskan agar memperingan Ybs.
> 
> Jadi jangan lupa update data denda nya sebelum klik "Selesai Transaksi" ya 😉

Terimakasih jawabannya pak.
Sudah dimodifikasi dengan menambah tabel baru pada database untuk menyimpan detail pembayaran dendanya 😊
