### ISSUE TITLE
Please contact system admin or change system environment to development at system module for more information about this error.

### ISSUE THREAD

**Issue by pandusomantri** [slims/slims9_bulian#231]
Saya install Slims 9 di cpanel, ketika saya klik **Add New Bibliography**
![image](https://github.com/slims/slims9_bulian/assets/103615228/bffbdf3f-ec81-44f6-969a-47f32039acdb)

ketika saya ubah ke **development**
![image](https://github.com/slims/slims9_bulian/assets/103615228/b5b36bdc-f65c-48cc-bcf2-1c026db92551)

muncul nya malah jadi error
![image](https://github.com/slims/slims9_bulian/assets/103615228/2d8b094e-5a0f-4e57-b893-4d9b0fd248a5)

mohon bantuan nya

**Comment by drajathasan** [comment]
Install ekstensi php FileInfo.

https://www.google.com/search?q=how+to+install+php+finfo+cpanel&sca_esv=8caeb1d653bc9a02&sxsrf=ACQVn0-EZVEcyKU0RHQ1oFIvf6xGORSasQ%3A1706703380435&ei=FDq6ZcyhGriNseMPkdK7qAM&ved=0ahUKEwjM--jFzYeEAxW4RmwGHRHpDjUQ4dUDCA8&uact=5&oq=how+to+install+php+finfo+cpanel&gs_lp=Egxnd3Mtd2l6LXNlcnAiH2hvdyB0byBpbnN0YWxsIHBocCBmaW5mbyBjcGFuZWwyCBAhGKABGMMEMggQIRigARjDBDIIECEYoAEYwwRIiRlQ9wdYshVwAXgBkAEAmAGSAqAB0QWqAQUwLjIuMrgBA8gBAPgBAcICChAAGEcY1gQYsAPCAgQQIxgnwgIKECEYChigARjDBOIDBBgAIEGIBgGQBgg&sclient=gws-wiz-serp

**Comment by pandusomantri** [comment]
terimakasih sudah bisa
