### ISSUE TITLE
Cannot add new system user or librarian 

### ISSUE THREAD

**Issue by sarlomie** [slims/slims9_bulian#233]
I am failing to add a new system user or librarian in a new installation using softaculous. The system does not return any error, it just will not save.

**Comment by linuxguist** [comment]
Hi @sarlomie , Just to help you : I also use softaculous apps installer and also c-panel in my servers. I knew from the SLiMS github repository, that SLiMS requires >=8.1 PHP Version. My C-Panel was showing 8.2 as the PHP Default version, in its Tools -> MultiPHP Manager. I just changed it to 8.1 PHP Version and SLiMS started working nicely on it. Please check if this is possible at your end too.

**Comment by sarlomie** [comment]
Thank you so much Nathan. Let me see if this will work.
