### ISSUE TITLE
Maximum possible length of an IPv6 address, expressed in human-readable form, is 39 characters

### ISSUE THREAD

**Issue by linuxguist** [slims/slims9_bulian#236]
First of all, Thank you very much for the wonderful SLiMS software. It is very helpful.

Secondly, one of my team members reported an issue in the Librarian Login.

He saw an incomplete error message.

I fixed it in the following ways : 

1. Changed env to development from production in the config/env.php file

2. This revealed more detailed error message, after logging in : 

Error : last_login_ip too long at row 1

3. I took a mysqldump of the database and noticed _ip field name existing in 3 tables, with maximum length at 20 / 15 characters, respectively.

4. I altered all the 3 tables, with the SQL given below : 

```

alter TABLE `user` MODIFY `last_login_ip` varchar(80) COLLATE utf8_unicode_ci DEFAULT NULL;

alter TABLE `member` MODIFY `last_login_ip` varchar(80) COLLATE utf8_unicode_ci DEFAULT NULL;

alter TABLE `files_read` MODIFY `client_ip` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL;

```

5. I asked Google Gemini about the maximum possible IPV6 address length and this is what it had to say : https://gemini.google.com/share/c218a4523b05

6. Also, my team member's IPV6 address at that time was : `fe80::8c6:46ac:7d64:1947%enp0s3`

7. After executing the alter table commands above, my team member was able to successfully login, without any errors.

Hope, this information is helpful for both the users and the development team. Thanks.

Best Regards,

Nathan S.R.

**Comment by drajathasan** [comment]
Thanks for your report. Which SLiMS version you use? Fyi this repo have two branch ```master``` and ```develop```, every update (also bug fix) will be available in branch ```develop```.

**Comment by linuxguist** [comment]
Hi, I use the v9.6.1 bulian production version.

**Comment by linuxguist** [comment]
Thanks. Had a look at the fix. Just wondering, if ``files_read` MODIFY `client_ip`` also needs to be included ? I am very eager to try out the develop branch on my server, at the earliest. Thanks for sharing info about this branch.

**Comment by linuxguist** [comment]
@drajathasan : Yes, I installed & checked the develop branch on my server, just now. Login was successful ! All the 3 _ip fields are having a varchar length of 50, as reported by phpmyadmin. Thanks for fixing it, at a lightning speed !!!!
