### ISSUE TITLE
Making Wildcard Search the default in Bibliography

### ISSUE THREAD

**Issue by linuxguist** [slims/slims9_bulian#239]
Hi, Thanks for the wonderful SLiMS Software.

Currently, in both v9.6.1 and the develop version, I find that, we need to add a * character, after a partial word search in bibliography, to fetch results, in the Librarian / Admin Login.

The OPAC search does not have this requirement and works well, fetching all records, that matches, partially too. Looks like, It is adding * OR % symbols automatically, before & after our keywords.

So, please make the Librarian's Bibliographic Search, equally powerful ! Thanks.

**Comment by drajathasan** [comment]
How about this? Everything is running well in development. SLiMS have two search engine, SearchBiblioEngine and DefaultEngine. Now both of them only running on OPAC. 

[Example]
with asterisk
https://youtu.be/q0dfhELiXwE?si=hVzZBJe8XAgzHH5z

With OR
![image](https://github.com/slims/slims9_bulian/assets/38057222/ef892850-3608-457a-8351-4e30d041ab21)

**Comment by linuxguist** [comment]
Thanks for the clarification ! BTW, if you just search for "Ranca" instead of "Rancangan", do you see the difference in Librarian's Bibliographic Search and the OPAC Search, even in the latest develop branch ? Our lay users may not know or use an asterisk, all the time. They just want their results fetched and shown.

**Comment by drajathasan** [comment]
> Thanks for the clarification ! BTW, if you just search for "Ranca" instead of "Rancangan", do you see the difference in Librarian's Bibliographic Search and the OPAC Search, even in the latest develop branch ? Our lay users may not know or use an asterisk, all the tim They just want their results fetched and shown.

Yes because they search engine in Librarian area is not same with opac. 

The solution for "lay users" is DefaultEngine. Change it in System Module at Search Engine section. 

For demo [check my video](https://youtu.be/bBnA74dImCQ?si=NjK_MUJ4nD3kc8VA)

**Comment by linuxguist** [comment]
Hi, Yes I have already toggled between the "DefaultEngine" and the "BiblioSearchEngine". Both are unable to retrieve any records, when search is done for a partial word. If OPAC search engine is available in the Librarian's login as well, it will be great. My users can easily & quickly search from 30,000 records and pick up what they want, for editing. However, if it is going to be a too much effort, for bringing that it in, then we can skip it, altogether.
