### ISSUE TITLE
Kindly respond to the e-mails sent to your official[at]slims[dot]web[dot]id from my e-mail id Nathan Sr <cquickcal[at]gmail[dot]com>

### ISSUE THREAD

**Issue by linuxguist** [slims/slims9_bulian#240]
I would like to contribute my efforts over the enhancement of PSLIMS and the slims.web.id website. So, I have sent you two emails, yesterday and the day before yesterday. Please check the same and let me know your feedback. Thanks.

**Comment by drajathasan** [comment]
Thanks for your contribution. Every modification from user is allow to distribute to other user and if you want it available in our web just make pull request. But, not all pull request will be merge to this repository.

**Comment by linuxguist** [comment]
Hi @drajathasan , Thanks for the quick reply. There are two things here : 1. I have given an enhanced professional look to the https://slims.web.id/web/ website, as shown in the screenshot below, in my efforts. Also, added some useful animations as well. I am enclosing a zip file of the whole thing here, as i am not that familiar with making pull requests. Secondly, for the PSLIMS, I have upgraded it to the latest development branch, along with provisioning of https support and automated service installer scripts ( can be now called as S-SLiMS :). The download size of this zip file is around 165 MB and the download link is https://sourceforge.net/projects/windows-slims-library-manage/files/latest/download  Please check if it is worthwhile to publish it on your website. There are always good free visual diff tools like kdiff3 to compare the changes that I have made, as against your existing files, very easily and quickly too.

<img width="1326" alt="Screenshot 2024-05-23 at 7 38 32 AM" src="https://github.com/slims/slims9_bulian/assets/122852451/10334f76-1abf-4130-a02d-fc069861ea88">
<img width="1326" alt="Screenshot 2024-05-23 at 7 38 47 AM" src="https://github.com/slims/slims9_bulian/assets/122852451/a252f85a-37de-4297-aa7e-e06890df11cd">

[slims_website_enhancement_suggestions_latest.zip](https://github.com/slims/slims9_bulian/files/15410592/slims_website_enhancement_suggestions_latest.zip)
