### ISSUE TITLE
Error al importar

### ISSUE THREAD

**Issue by Rociolatorre** [slims/slims9_bulian#241]
Hi,

I am currently trying to import a file into the library and I get an error that it is deprecated, I cannot activate it, what can I do to import:

Deprecated: Creating the dynamic property SLiMS\Csv\Reader::$standart is deprecated in /home2/colegi20/public_html/biblioteca/lib/Csv/Reader.php on line 25
[senayan_item_export (1).csv](https://github.com/slims/slims9_bulian/files/15404882/senayan_item_export.1.csv)
![captura importar](https://github.com/slims/slims9_bulian/assets/170543370/51673f6f-5fb2-4504-a56f-71f08e9b1598)

I hope you can help me solve it

**Comment by drajathasan** [comment]
It just deprecated. Go to System, open System Environement Setting, change Development to Production and that "deprecated" will not appear.

**Comment by Rociolatorre** [comment]
No, it is an error when importing, how do I solve it?

**Comment by drajathasan** [comment]
> No, it is an error when importing, how do I solve it?

open System Environement Setting, change Development to Production and that "deprecated" will not appear.
