### ISSUE TITLE
SLIMS 9.6.1 Error 500 Visitor Counter URL : /admin/modules/reporting/customs/visitor_list.php 

### ISSUE THREAD

**Issue by adojrable** [slims/slims9_bulian#243]
I got error Visitor Counter after upgraded SLIMS  9.5.2 to 9.6.1
is there anyone can help?

![Error 500 Counter Slims](https://github.com/slims/slims9_bulian/assets/41410908/6c34dce9-28d5-42c7-b316-600a304b682e)

**Comment by drajathasan** [comment]
GO to module system, click on "System Environment Setting" change Production to Development then save. Back to the last menu, and you will get an error message, screenshot it into this comment.

**Comment by adojrable** [comment]
> GO to module system, click on "System Environment Setting" change Production to Development then save. Back to the last menu, and you will get an error message, screenshot it into this comment.

![image](https://github.com/slims/slims9_bulian/assets/41410908/152ab9c9-78c1-42f9-a2d1-a0438fff9acc)

**Comment by drajathasan** [comment]
may be it can help you

https://stackoverflow.com/questions/1846882/open-basedir-restriction-in-effect-file-is-not-within-the-allowed-paths

**Comment by Opsnatt** [comment]
cara benerinnya gimana min? erorr 500 juga disini /admin/modules/reporting/customs/visitor_list.php
visitor gak bisa terekam padahal ID sudah sesuai

**Comment by Opsnatt** [comment]
![Image](https://github.com/user-attachments/assets/76d81cd7-9cbe-40bc-a31e-c45fa28cd82c)

**Comment by Opsnatt** [comment]
![Image](https://github.com/user-attachments/assets/aa7dca8b-7c97-4ce6-8fbb-b9505d8b0fba)
