### ISSUE TITLE
tidak bisa menambahakan penerbit baru dan klasifikasi di slims 9

### ISSUE THREAD

**Issue by PerpustakaanCahayaSMAN1BT** [slims/slims9_bulian#245]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by drajathasan** [comment]
Apakah SLiMS nya sudah online?

**Comment by PerpustakaanCahayaSMAN1BT** [comment]
slims nya sudah online , versi 9   permasalahan  muncul ketika ingin mengisi kolom penerbit dan klasifikasi tidak bisa di isikan
![123](https://github.com/slims/slims9_bulian/assets/172340283/6f4a51a8-04c2-41ac-b90d-823b8dc2b14d)

**Comment by drajathasan** [comment]
Untuk saat ini gunakan plugin https://github.com/drajathasan/slims-chosen-modsec, pastikan tidak ada plugin lain yang berjalan di form biblio karena plugin tersebut tidak bisa berjalan bersama plugin yang lain.
