### ISSUE TITLE
Request for adding Item_Code field in Bibliography List Page for  viewing Sorted data using this field 

### ISSUE THREAD

**Issue by AnandAgasty** [slims/slims9_bulian#246]
Presently there are Title, ISBN/ISSN, Copies, and Last Update fields on Bibliography List Page. 
We can sort the data (Ascending/Descending) only through these fields.
It is requested for either 
(1) adding field Item_Code field in Bibliography List Page 
OR 
(2) replacing the Copies field with Item_Code field
as the Item_Code field is more familiar for me to view the sorted data.
Thanks.

**Comment by AnandAgasty** [comment]
Just I have noticed that the Item_Code field is listed in Item List Module and sorting is possible there. My purpose is fulfilled. Thanks for everything.

**Comment by linuxguist** [comment]
Hi @drajathasan , As per the enclosed PDF manual of slims, which I obtained through Google search, it is clearly mentioned that item code is also known as accession number, in various countries. So, please add accession number besides item code in the slims user manual, for the benefit of all. Thanks a lot.

[slims_add_new_entry_tutorial_apu.pdf](https://github.com/user-attachments/files/15855671/slims_add_new_entry_tutorial_apu.pdf)
