### ISSUE TITLE
Any idea if a French translation is currently in the works?

### ISSUE THREAD

**Issue by dleigh** [slims/slims9_bulian#248]
Looking to see if SLIMS might be a good fit for a small private school in France. I see the multiple translations but not yet in French.  Just wondering if anyone is currently working on that?  I'm not a native speaker unfortunately.

**Comment by drajathasan** [comment]
Hi @dleigh. SLiMS translation is powered by Gettext library. If you like to translate SLiMS into French you can follow this video

[How to translate SLiMS to another Language with POEDIT](https://youtu.be/QglyQJnB1Rs)

**Comment by dleigh** [comment]
Ok - thanks!



------ Original Message ------
From "Drajat Hasan" ***@***.***>
To "slims/slims9_bulian" ***@***.***>
Cc "David Leigh" ***@***.***>; "Mention" 
***@***.***>
Date 2024-07-25 18:14:38
Subject Re: [slims/slims9_bulian] Any idea if a French translation is 
currently in the works? (Issue #248)
