### ISSUE TITLE
Tidak dapat Login Admin/Pustakawan

### ISSUE THREAD

**Issue by LTPerpustakaanSMAN1** [slims/slims9_bulian#250]
![image](https://github.com/user-attachments/assets/a4632893-0ebc-46bb-9560-aeb1e6d1f43a)
Mohon bantuannya, sudah 4 jam lebih user admin dan super admin tidak dapat login. setiap memasukkan uname dan password, akan kembali ke halaman login.

**Comment by drajathasan** [comment]
1. Apakah SLiMS nya online?
2. Apakah pernah melakukan modifikasi terhadap SLiMS yang sekarang digunakan?
3. Pesan error apa yang muncul ketika tidak berhasil login?

**Comment by LTPerpustakaanSMAN1** [comment]
1. Iya, SLiMS yang digunakan telah di-online-kan
2. modifikasi yang dilakukan hanya penambahan plugin label barcode dan kantong buku
3. tidak ada notifikasi error apapun, hanya saja semua akun tidak dapat login, mau itu melalui komputer ataupun ponsel

hari ini pun tidak dapat login, walaupun sudah menggunakan berbagai browser dan private browser. mohon bantuannya, terima kasih.

**Comment by drajathasan** [comment]
Apakah sebelumnya SLiMS dipindah dari hosting yang lain ke hosting yang sekarang? Terlihat dari indikasi diatas bahwa anda yang bermasalah dari sisi hosting nya seperti

1. Session handlernya
2. Session tidak dapat di buat karena folder nya tidak ada atau tidak bisa ditulis
3. dll.

**Comment by K-Kaio** [comment]
Saya juga terjadi hal yang sama, saya baru menginstal mengikuti tutorial yang ada di yt, dan saat mencoba login tidak muncul apa-apa seperti divideo tutorial yang langsung muncul ke beranda

**Comment by LTPerpustakaanSMAN1** [comment]
Syukurnya sudah bisa. ternyata storage yang penuh berpengaruh untuk proses loginnya. terimakasih untuk bantuannya.
