### ISSUE TITLE
Uncaught (in promise) SyntaxError: Unexpected token '<', "<div style"... is not valid JSON

### ISSUE THREAD

**Issue by gusfahmi** [slims/slims9_bulian#251]
**Describe the bug**
Semua data telah diupload, cuma datanya gk muncul di frontend

**To Reproduce**
1. Go to repositori.poltekbangmedan.ac.id
2. Buka tab console
3. See error

**Expected behavior**
data dapat muncul di frontend

**Screenshots**
![slims](https://github.com/user-attachments/assets/9b91a560-f300-4400-98d2-ddaa6b32d064)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version -

**Comment by drajathasan** [comment]
Pastikan slims atau aplikasi yang satu hosting dengan SLiMS dalam kondisi sehat ya (tidak terkena virus, malware, spyware)

Berikut penyebab kenapa gak muncul di frontend (akses pada gambar : https://repositori.poltekbangmedan.ac.id/index.php?p=api/subject/popular).

![image](https://github.com/user-attachments/assets/012edd1e-3027-4799-939d-7b1a2ef6d035)
