### ISSUE TITLE
IFRAME blocked by server, many functions not working anymore

### ISSUE THREAD

**Issue by harrishariadi** [slims/slims9_bulian#255]
Since the server is blocking IFRAME by automatically replacing <iframe> tag with XXXXX, many functions that depend on it stop working. FYI, I do not have control over the server. Please help.
![image](https://github.com/user-attachments/assets/64ec9f8a-b016-4ce2-92df-fb462a05f632)

**Comment by drajathasan** [comment]
This is not bug, this is a netowrk policy problem.
