### ISSUE TITLE
Foto anggota tidak ditampilkan (ditampilkan hanya sebagian)

### ISSUE THREAD

**Issue by Anry08** [slims/slims9_bulian#256]
Describe 
Issue terjadi di Slims 9.6.1 (bulian),
foto anggota ada yang tidak ditampilkan dan ada yang ditampilkan, di folder image/person ada semua. Foto diambil secara langsung dari aplikasi slims nya. Saya sudah mencoba reupload ulang ada yang berhasil, ada yang ketika reupload gagal dan berakibat foto tidak tampil bahkan folder image/person terhapus dengan sendirinya.

Solusi yang telah dilakukan :
1. Ganti browser, masalah masih ada foto ada yang sebagian ada yang tampil, sebagian lagi ada yang tidak tampil
2. Clear cache di browser
3. reupload ulang ada yang berhasil ada yang tidak

Screenshots
![Screenshot (19)](https://github.com/user-attachments/assets/3366485d-cc18-4c09-9cbc-72b1c80a508b)

Desktop 
 - Windows 11 pro
 - Browser chrome
 - Slims 9.6.1
 - Laragon 6.0

Mohon bantuannya untuk mengatasi permasalahan tersebut.

**Comment by drajathasan** [comment]
Ketika ga berhasil apa pesannya?

**Comment by Anry08** [comment]
> Ketika ga berhasil apa pesan error nya?

pesan error nya saya lupa tidak screenshoot, tapi kalau seingat saya image size too large atau sejenisnya begitu mas. Padahal image atau foto yang saya ambil lewat webcam yg diambil dari slims nya langsung bukan file image dari luar.

**Comment by drajathasan** [comment]
Kalau dari webcam, kadang size nya besar kak. Setahu saya dibatasi hanyak 500KB saja.

**Comment by Anry08** [comment]
> Kalau dari webcam, kadang size nya besar kak. Setahu saya dibatasi hanyak 500KB saja.

iya mas, saya ambil dari webcam yang dicolokan langsung ke slims nya. Barusan saya check ukuran file foto di folder nya size sekitar 70-80 KB saya rasa ini ukuran yang masih bisa dikompromi di slims nya, tapi masalahnya fotonya ada sebagian tampil ada yg tidak di slims nya

**Comment by drajathasan** [comment]
Baik terimakasih untuk laporannya. Saat ini sudah diperbaiki diversi develop dan juga akan dirilis pada versi berikut nya.

Bisa dicoba upgrade ke versi develop di komputer lokal atau folder lain dengan data yang sekadang digunakan.

https://github.com/slims/slims9_bulian/archive/refs/heads/develop.zip

**Comment by Anry08** [comment]
> Baik terimakasih untuk laporannya. Saat ini sudah diperbaiki diversi develop dan juga akan dirilis pada versi berikut nya.
> 
> Bisa dicoba upgrade ke versi develop di komputer lokal atau folder lain dengan data yang sekadang digunakan.
> 
> https://github.com/slims/slims9_bulian/archive/refs/heads/develop.zip

ini harus upgrade ke versi develop ya?

**Comment by buitenzorg812** [comment]
> Baik terimakasih untuk laporannya. Saat ini sudah diperbaiki diversi develop dan juga akan dirilis pada versi berikut nya.
> 
> Bisa dicoba upgrade ke versi develop di komputer lokal atau folder lain dengan data yang sekadang digunakan.
> 
> https://github.com/slims/slims9_bulian/archive/refs/heads/develop.zip

Sudah diperbaiki.
