### ISSUE TITLE
Galat Menu Admin pada : slims/develop

### ISSUE THREAD

**Issue by awriel** [slims/slims9_bulian#26]
[SOLVED]
**Describe the bug**
Muncul galat: 

`Fatal error: Uncaught Error: Class 'Ramsey\Uuid\Uuid' not found in /opt/lampp/htdocs/slims9_bulian/lib/AdvancedLogging.php:71 Stack trace: #0 /opt/lampp/htdocs/slims9_bulian/lib/AlLibrarian.php(30): SLiMS\AdvancedLogging->setUuid() #1 /opt/lampp/htdocs/slims9_bulian/admin/index.php(71): SLiMS\AlLibrarian->__construct('1101', Array) #2 {main} thrown in /opt/lampp/htdocs/slims9_bulian/lib/AdvancedLogging.php on line 71`

Ketika di Beranda Admin hendak memilih seluruh menu yang ada pada Admin SLiMS pada slims/develop

**Desktop + Server:**
- OS: Manjaro KDE 20.x
- Browser: Firefox 77.01
- XAMPP Linux 7.4.7
  -  Apache/2.4.43 (Unix) OpenSSL/1.1.1g PHP/7.4.7 mod_perl/2.0.11 Perl/v5.30.3
  -  Database client version: libmysql - mysqlnd 7.4.7
  -  PHP extension: mysqli  curl  mbstring 
  -  PHP version: 7.4.7 

**Additional context**
Galat ini muncul ketika menggunakan branch slims/develop, ketika kembalikan ke branch slims/master, permasalahan ini tidak muncul

**Comment by awriel** [comment]
Fatal error: Uncaught Error: Class 'Ramsey\Uuid\Uuid' not found in /opt/lampp/htdocs/slims9_bulian
`/lib/AdvancedLogging.php:71 Stack trace: #0 /opt/lampp/htdocs/slims9_bulian/lib/AlLibrarian.php(30): SLiMS\AdvancedLogging->setUuid() #1 /opt/lampp/htdocs/slims9_bulian/admin/modules/bibliography/index.php(1060): SLiMS\AlLibrarian->__construct('1151', Array) #2 {main} thrown in /opt/lampp/htdocs/slims9_bulian/lib/AdvancedLogging.php on line 71`
Muncul juga ketika coba akses Daftar Bibliography 
![Screenshot_20200630_122011](https://user-images.githubusercontent.com/120725/86086419-ecab5400-bacb-11ea-9602-4243b9359aaf.png)

**Comment by heroesoebekti** [comment]
coba dijalankan `composer install` di direktori slims mas @awriel

**Comment by awriel** [comment]
Terima kasih Mas @heroesoebekti. It's work!
