### ISSUE TITLE
pencetakan label barcode tidak ada

### ISSUE THREAD

**Issue by Febrianto0202** [slims/slims9_bulian#27]
Hallo Slims. 
disini saya menemukan bug. sy menggunakan slims 9 bulian.
ada masalah waktu pencetak label salah satunya barcode tidak ikut tercetak.

![Cuplikan layar dari 2020-09-02 04-32-57](https://user-images.githubusercontent.com/56257569/91958507-726a9c00-ecd5-11ea-8c22-24a96ef4b546.png)

Tools yang saya gunakan :
1. Docker
2. Mariadb
3. Nginx
4. Php versi 7.4
5. Linux Centos 8.x

Thanks,

**Comment by heroesoebekti** [comment]
halo kak @Febrianto0202 , untuk label dan barcode secara default memang belum tersedia di slims semua versi

**Comment by Febrianto0202** [comment]
Hallo..
bukannya secara default ada yaa kak, 
sy coba di slim 7 cendana bisa cetak label barcode 

![2](https://user-images.githubusercontent.com/56257569/92070036-fcb80c00-ed78-11ea-85b6-ce6e026e4bbc.png)

**Comment by idoalit** [comment]
Secara default SLiMS tidak memiliki fitur label dengan barcode yang menyatu. @Febrianto0202 bisa menambahkannya sendiri, baik itu custom sendiri atau mencari di https://slims.web.id/goslims
