### ISSUE TITLE
Penambahan menu baru label barcode

### ISSUE THREAD

**Issue by Febrianto0202** [slims/slims9_bulian#28]
Dear Slims.
Terimakasih atas apllikasi slims9 bulian, hasilnya sangat bagus.
Saya punya saran bagaimana kedepannya kami dapat menginstall aplikasi  slims di server hosting dan menambahkan menu baru yaitu menu "Label dan barcode", yang nantinya akan menampilkan barcode beserta labelnya.
Dan kami berharap penambahan menu tersebut sudah diupdate/upgrade di versi selanjutnya .

Mohon maaf, mungkin saran saya ini terlalu berlebihan.
Terima kasih.

Ttd
Febrianto M ipu.

**Comment by idoalit** [comment]
It's available in SLiMS 9.3 as plugins
