### ISSUE TITLE
Error_connection_timed_out save Pustakawan di sistem

### ISSUE THREAD

**Issue by KamaludinZ** [slims/slims9_bulian#32]
![Screenshot_2020-09-14-15-07-22-40](https://user-images.githubusercontent.com/63649095/93060456-5a632700-f69c-11ea-9fa5-8235652e43cc.jpg)

Untuk semua data ketika di save sudah dapat menyimpan dan berjalan lancar. Tapi tidak untuk ketika saya mencoba menambahkan pustakawan pada sistem. Tombol simpan tidak bisa merepon. Dan tidak bisa menyimpan. Dan akhirnya ketika di refresh akan tampil seperti di gambar. Sayangnya hal ini terjadi pada hosting yg saya pakai. Ketika saya tanyakan kepada penyedia hosting, dia mengatakan bahwa tidak terjadi apa2.

**Comment by buitenzorg812** [comment]
coba diinspect element, pak. klik tab network, kemudian lakukan penambahan pustakawan. lihat pesan error yang ditemukan pada inspect element.

**Comment by KamaludinZ** [comment]
[image: image.png]

seperti ini pak. dan setiap kali ini terjadi DNS kami semacam terkena blok.
jadinya semisal akses wifi yg kita akses sama, kita buka di laptop
lainpun nantinya juga akan tampil yg sama. seperti gambar saya yg pertama.
berikut :

[image: image.png]

Pada tanggal Sen, 14 Sep 2020 pukul 17.18 Arif Syamsudin <
notifications@github.com> menulis:

**Comment by idoalit** [comment]
Issue ada di jaringan anda, bukan di aplikasi.
