### ISSUE TITLE
Version number not updated in sysconfig.inc.php and also environment is set to development in Slims 9.2.0 release package

### ISSUE THREAD

**Issue by prbt2016** [slims/slims9_bulian#33]
Hello,

I downloaded Slims 9.2.0 from here :  

https://github.com/slims/slims9_bulian/releases/download/v9.2.0/slims9_bulian-9.2.0.zip

However, I found that in sysconfig.inc.php that the version number is not updated i.e : 

`define('SENAYAN_VERSION_TAG', 'v9.1.1');`

instead of 

`define('SENAYAN_VERSION_TAG', 'v9.2.0');`

Also, the environment is set to development instead of production i.e : 

`define('ENVIRONMENT', 'development');`

instead of 

`define('ENVIRONMENT', 'production');`

Could you please fix  this ?.

**Comment by buitenzorg812** [comment]
updated. thank you.

**Comment by prbt2016** [comment]
Hello @buitenzorg812 ,

Thanks for the change. But seems that this isn't changed 

`define('ENVIRONMENT', 'development');` 

to 

`define('ENVIRONMENT', 'production');` 

Could you please make this change as well. In previous version 9.1.1 this was set to 'production'.
