### ISSUE TITLE
file PDF saat Online

### ISSUE THREAD

**Issue by shoelyshtya** [slims/slims9_bulian#4]
<a href="https://ibb.co/TWP4hfv"><img src="https://i.ibb.co/CPVb0c1/Untitled.png" alt="Untitled" border="0"></a>

**Comment by buitenzorg812** [comment]
![screenshot-slimsjkt hasandigital id-2020 02 10-15_20_20](https://user-images.githubusercontent.com/125229/74132371-02050c00-4c19-11ea-82a5-04b5e93e8248.png)
di server online kami, berkas pdf dapat dika dengan baik, kak. apakah masalah koneksi internet?

**Comment by slims** [comment]
@shoelyshtya jika anda hendak mencantumkan sebuah issue, silahkan dijelaskan kendala yang dihadapi, hal apa yang sudah pernah dilakukan, dan tanggkapan layar sebagai bahan pendukung. Jika SLiMS anda sudah online mungkin bisa dicantumkan URL untuk dapat dicek secara langsung. Karena tidak semua error berasal dari aplikasi, namun bisa juga dari pengaturan webserver yang digunakan. Terima kasih.
