### ISSUE TITLE
New member log in fail

### ISSUE THREAD

**Issue by matinalsun** [slims/slims9_bulian#57]
I install slims through "web station" and use mariadb10 as a database. I can log in with the user I add when installing slims. But when I add a new member, I found that my password in the database becomes a mass like this: "$2y$10$if6n8bmjL2vurqtB7HuDa.aGF2ARRsQjYO1Z3OdS.xdg4li4VVIE2"
I tried to login to new members through the password I add through the first librarian user or showing in the database. But all failed.

**Comment by matinalsun** [comment]
Sames Database error

**Comment by matinalsun** [comment]
It seems that only users can be added. Members cannot log in. Is there any switch to allow members to log in ?

**Comment by mucill** [comment]
The answer is yes, and already activated by default. So, any new member with a password, will have a privileged to access the member's page in OPAC, but not allowed to access the Admin's page. Its different purpose.
And the password that you have shown above, was not the real password but the encrypted password. You need to remember the real password, not the encrypted one. You can change the member password from admin page. Just edit the member information and find the New Password form below, then save it. I hope this is helpful. Thank you

**Comment by matinalsun** [comment]
Thanks for your answer!
