### ISSUE TITLE
Cannot search keywords less than 3 characters

### ISSUE THREAD

**Issue by matinalsun** [slims/slims9_bulian#63]
**Describe the bug**
The search function can't resolve keywords for less than 3 characters. 
For instance, it can return an appropriate result if I search for "Ajax" but return null if I search for "PHP".  I wonder is there any code to limit the character number of keywords. If it exists I want to change it to 2.
Besides, The search engine cannot resolve a title that includes lots of compound words. Which are very common in Japanese, Chinese, and German books. Is there any solution to handle these compound words? For example, it can return "Donaudampfschifffahrtsgesellschaftskapitänswitwe" when I search for "schaftskapitän" :-)

**Comment by za** [comment]
Hi @matinalsun do you see any ERROR message? Can you paste it here if any?

**Comment by matinalsun** [comment]
> Hi @matinalsun do you see any ERROR message? Can you paste it here if any?

DevTools failed to load SourceMap: Could not load content for http://192.168.1.88:2333/template/default/assets/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

That's all in the console when I search for some keywords. Is there any other information I can find in some place?

**Comment by matinalsun** [comment]
Excuse me. Could you please tell me where the search function realized in the source code? I can debug the function myself if I know how it works.

**Comment by matinalsun** [comment]
> Hi @matinalsun do you see any ERROR message? Can you paste it here if any?

I have found the reason. The 3 characters problem was caused by SQL itself. I solved it by change ft_min_word_len=1. And it seems that MATCH AGAINST can not resolve non-English characters so I changed it to LIKE.
