### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by adhity4** [slims/slims9_bulian#64]
Plugin ketika membuat modul baru plugin data maksimal yang tampil cuma 3

**Comment by heroesoebekti** [comment]
Mohon gunakan template issue yang sudah disediakan untuk membuat issue bug. Terima kasih

**Comment by adhity4** [comment]
> Mohon gunakan template issue yang sudah disediakan untuk membuat issue bug. Terima kasih
udah clear kok kak aku hapus limit 3 nya
