### ISSUE TITLE
Error 500 on admin index.php?mod= request

### ISSUE THREAD

**Issue by ImBIOS** [slims/slims9_bulian#67]
**Describe the bug**
Get Http 500 error response on clicking the admin top menu

**To Reproduce**
1. Go to 'admin page'
2. Click on 'any menu on the top menu of the admin page'
3. See an error

**Expected behavior**
When clicked bibliography, it should be bibliography showed up.

**Desktop:**
 - OS: Windows
 - Browser chrome
 - Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by wynerst** [comment]
Error server 500 is too generic to understand the problem.
It can also mean that the problem come from your server not from the program as i quote:
"The HyperText Transfer Protocol (HTTP) 500 Internal Server Error server error response code indicates that the server encountered an unexpected condition that prevented it from fulfilling the request.
This error response is a generic "catch-all" response. Usually, this indicates the server cannot find a better 5xx error code to response. Sometimes, server administrators log error responses like the 500 status code with more details about the request to prevent the error from happening again in the future."
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
