### ISSUE TITLE
Extend search by keywords

### ISSUE THREAD

**Issue by 0xD0M1M0** [slims/slims9_bulian#68]
**Is your feature request related to a problem? Please describe.**
I tried the simple keyword word search from the default template. I tried author or a word in the notes abstract. I recieve no results.

**Describe the solution you'd like**
I added the feature of publisher and notes/abstract search, but I was wondering, if there is a reason, why the keyword search is limited. If there are no reasons, I would like to create the pull request to add keyword search for publisher and abstract/notes fields.

**Describe alternatives you've considered**
At least allow additional search options in the advanced search if database load would be to big if the keywords search would have more columns to search into.

**Additional context**
-

**Comment by liwenjing93** [comment]
Dear, I think this would be the answer:  https://github.com/slims/slims9_bulian/issues/86
