### ISSUE TITLE
Option FollowSymLinks not allowed here, centos server & plesk panel

### ISSUE THREAD

**Issue by Marzuki5** [slims/slims9_bulian#74]
apakah ini bug atau konfigurasi server yang salah. terimakasih,

sepesifikasi : 
php 7.4 
mariadb 5.7 
os sever : centos 7
cpanel : plesk

**Comment by idoalit** [comment]
Ini bukan bug, tapi tergantung konfigurasi web server anda. silahkan ikuti link berikut [https://wiki.centos-webpanel.com/options-followsymlinks-not-allowed](https://wiki.centos-webpanel.com/options-followsymlinks-not-allowed) untuk info lebih lanjut.
