### ISSUE TITLE
unexpected 'array' in lib/Plugins.php

### ISSUE THREAD

**Issue by 0xD0M1M0** [slims/slims9_bulian#78]
**Describe the bug**
After updating the files from 9.3.0 to 9.4.1, I get the following error and cannot enter the side anymore:
Parse error: syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST) in [...]/lib/Plugins.php on line 22

**To Reproduce**
If I uncomment \SLiMS\Plugins::getInstance()->loadPlugins(); from sysconfig.inc.php, the error stops on the frontend but the backend is still blocked.

**Expected behavior**
Use of webservice without error.

**Comment by buitenzorg812** [comment]
How did you make the upgrade exactly? I have also made experiment of upgrading from 9.3.0 to 9.4.1. and the upgrade process done without failure. did you use php7.4 with 9.4.1 code? 9.4.1 minimum requirement is php7.4 though.

![image](https://user-images.githubusercontent.com/125229/115955313-f3ee9300-a51f-11eb-8e02-080abf8c0fb1.png)

**Comment by 0xD0M1M0** [comment]
Well, I found nowhere (at least in English) a description how to upgrade. The upgrade script in the install folder does not activate as the config file is already existing. If I uncomment this, the installer does not pass the first screen. So I copied all files and ran the, I believe, 3 commands from the upgrade for the database.

**Comment by idoalit** [comment]
Remove your config/sysconf.local.inc.php and run upgrade again via SLiMS Installer.

**Comment by 0xD0M1M0** [comment]
Thank you. Solved my problem.

It's important to say, that the manual and specific changes in "config/sysconf.local.inc.php" shall be saved and copied inside the file again.
