### ISSUE TITLE
Pencarian berdasarkan subjek di OPAC

### ISSUE THREAD

**Issue by pustakawan** [slims/slims9_bulian#8]
Pencarian berdasarkan subjek di opac, setelah upgrade dari slims8.3.1 ke slims9_bulian tidak ada data ditemukan, sebelumnya waktu menggunakan slims8.3.1 data nya ada.

**Comment by buitenzorg812** [comment]
halo, kak. coba kakak indeks ulang lewat modul system > biblio indexes > emptying index && re-create index.

**Comment by pustakawan** [comment]
Baik, akan saya coba terima kasih.

Dikirim dari Yahoo Mail di Android 
 
  Pada Sab, 29 Feb 2020 pada 10:25, Arif Syamsudin<notifications@github.com> menulis:   
halo, kak. coba kakak indeks ulang lewat modul system > biblio indexes > emptying index && re-create index.

**Comment by slims** [comment]
Mohon gunakan template issue yang sudah disediakan, agar kami bisa mengetahui permasalahan yang terjadi dengan lebih jelas. Terima kasih.
