### ISSUE TITLE
Tidak bisa membuat dan perbarui pengguna di MySQL8

### ISSUE THREAD

**Issue by awriel** [slims/slims9_bulian#80]
**Screenshots**
I![image](https://user-images.githubusercontent.com/120725/115950226-3bffbc80-a504-11eb-83ed-75b74e8a6108.png)

**Desktop (please complete the following information):**
 
![image](https://user-images.githubusercontent.com/120725/115950287-85e8a280-a504-11eb-8c5d-114fea0cd6af.png)

**Describe the bug**
Tidak bisa update atau create user baru ketika menggunakan MySQL 8

**Comment by buitenzorg812** [comment]
You can't use mysql 8 at the moment. SLiMS 9 Bulian hasn't been made compatible with this version mysql.
