### ISSUE TITLE
Could not replace a language from the existing one

### ISSUE THREAD

**Issue by liwenjing93** [slims/slims9_bulian#81]
Hello everyone, I installed slims 9 on my website, there are many languages but there is no my language. I was trying to replace the existing language (Arabic) to my language (vietnamese) by editting the file **messages.po**. The path is:
**"\slims9_bulian-9.1.1\lib\lang\locale\ar_SA\LC_MESSAGES\messages.po".**

After editting, I uploaded and replaced the file "messages.po" in my hosting with the same Path. After that, I accessed my website, selected Arabic in the menu, refreshed my website but the language in the content is still Arabic, the text that I replaced doesn't change. I tried to clear cache, delete cookie on Browser chrome but it is still like that. Please see the Screenshot below:

![Screenshot_5](https://user-images.githubusercontent.com/9654732/116045672-72703f80-a69c-11eb-843b-a97d6a8bf0da.png)

![image](https://user-images.githubusercontent.com/9654732/116046396-3a1d3100-a69d-11eb-8633-adeeb89cfaee.png)

I hope you guys can give me an simple solution to translate new language. I can translate it by myself but I do not know where to do.

Thank you guys very much!

------------------- Some information from my end:

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Google Chrome:
Version 90.0.4430.72 (Official Build) (64-bit)

**Comment by buitenzorg812** [comment]
you might need to consider using poedit in for working with .po files.

**Comment by heroesoebekti** [comment]
first you have to create a new folder in the **\slims9_bulian-9.1.1\lib\lang\locale**  folder with a name according to the language code that you will use.

for reference use this site to find language codes [http://www.lingoes.net/en/translator/langcode.htm](http://www.lingoes.net/en/translator/langcode.htm)

![langcode](https://user-images.githubusercontent.com/2249323/121052558-b0589b80-c7e4-11eb-846b-c0f3e7b0803a.png)

Next change the file **\slims9_bulian-9.1.1\lib\lang\lang\localisation.php** by adding the code below 

`$available_languages[] = array('vi_VN', __('Vietnamese'), 'Viet Nam');`

![tes](https://user-images.githubusercontent.com/2249323/121053655-c7e45400-c7e5-11eb-904f-9a32ae83f597.png)

then you can move the translated **_LC_MESSAGES_** folder into the folder you just created (**\slims9_bulian-9.1.1\lib\lang\locale\vi_VN** folder) 

![result](https://user-images.githubusercontent.com/2249323/121055167-3bd32c00-c7e7-11eb-9842-5883a7a3bf6c.png)
