### ISSUE TITLE
Database loan dari localhost tidak bisa di-copy ke database online

### ISSUE THREAD

**Issue by sabbathnatalie** [slims/slims9_bulian#82]
Saya upgrade dari akasia ke bulian 9.0.0 di localhost dan ingin coba mengonlinekan slims bulian.
Sudah install aplikasi bulian dari softaculous.
Saat copy database, data loan tidak bisa di-copy dan muncul pesan eror berikut.
Sejauh ini database lainnya bisa di-copy.
Mohon bantuannya.

![slimstrouble](https://user-images.githubusercontent.com/84700086/119305320-c9186b80-bc92-11eb-927f-f5cd5b2f6b71.png)

**Comment by heroesoebekti** [comment]
dari pesan galat `bibllio_id cannot be null`, artinya kemungkinan koleksi yang dipinjam tidak ada relasi dengan biblio / eksemplar karena biblio/eksemplar sudah terhapus tetapi nomor eksemplar masih tercatat di peminjaman

**Comment by sabbathnatalie** [comment]
Terima kasih infonya. Apakah ada cara lain agar data loan bisa dicopy?

**Comment by sabbathnatalie** [comment]
akhirnya saya pindahkan (move) tabelnya. data peminjaman sudah bisa masuk.
