### ISSUE TITLE
Bibliography Attachment Still Accessible even after it has set only to member type

### ISSUE THREAD

**Issue by erichps114** [slims/slims9_bulian#84]
Hi dev,
I am adding new bibliography attachment. It was set to specific member type.
![image](https://user-images.githubusercontent.com/46837969/121013375-54cde400-c7cb-11eb-92c6-e53d30bd677b.png)

But after saving the changes, all member still could access those attachment even unregistered visitor.
![image](https://user-images.githubusercontent.com/46837969/121013595-9d859d00-c7cb-11eb-998f-082402288a27.png)

**Comment by buitenzorg812** [comment]
it's not a bug. slims cannot protect (even with member type) any attachment in form of link.

**Comment by nalamapu** [comment]
I don't see any problem. It works for me. Any file having **Access Limit by Member Type** prompts users to login.

**Comment by erichps114** [comment]
> 
> 
> it's not a bug. slims cannot protect (even with member type) any attachment in form of link.

Ok then.
