### ISSUE TITLE
Searching in OPAC with less than 3 keywords

### ISSUE THREAD

**Issue by liwenjing93** [slims/slims9_bulian#86]
Dear SLIMS dev team,

I see we can not search on OPAC with less than 3 keywords in any language. After research now I know how to fix it and I hope you guys can add a button that we can change it easily. 

Here is how to change it:

in: \public_html\config , open the file: sysconfig.local.inc.php , then change "index" to "default"

![image](https://user-images.githubusercontent.com/9654732/121335151-8918e000-c944-11eb-899a-af46771421bc.png)

Done. 

Thanks!

**Comment by wynerst** [comment]
Your steps will not solve the problem entirely, unless you already change your MySQL/MariaDB system settings.
Please read this reference https://dev.mysql.com/doc/refman/8.0/en/fulltext-fine-tuning.html
Therefore, adding button on SLiMS as you suggestions is not viable.
