### ISSUE TITLE
How to change the admin password?

### ISSUE THREAD

**Issue by liwenjing93** [slims/slims9_bulian#93]
Hi Slims Dev Team, 

I could not find where to change the admin password. I read your documentation but could not find where is the **User table?** in phpmyadmin. I hope you guys could help me with this. Thanks in advance!!!

Besides, if you guys could add a button in the setting of slims that could help administrators change it easily it would be great!

![image](https://user-images.githubusercontent.com/9654732/123889915-96901b80-d980-11eb-8dda-f24f7390cfb0.png)

![image](https://user-images.githubusercontent.com/9654732/123890555-96dce680-d981-11eb-94db-7c47453de463.png)

![image](https://user-images.githubusercontent.com/9654732/123890537-8f1d4200-d981-11eb-8036-c435696f0748.png)

**Comment by heroesoebekti** [comment]
![Screenshot 2021-06-30 at 22-44-54 perpus wiraraja ac id localhost phpMyAdmin 4 5 4 1deb2ubuntu2 1](https://user-images.githubusercontent.com/2249323/123991556-07711b00-d9f5-11eb-805b-243427413944.png)
please read carefully, click next page
