### ISSUE TITLE
Could not search books with "Items Data" 

### ISSUE THREAD

**Issue by liwenjing93** [slims/slims9_bulian#95]
Hi dev team, 

I am able to search books with: Title, author, ISBN... However, I could not search books with "Item(s) Data".  This is important because our library can use a barcode to scan books quickly with those Items data that we created. Can you guys tell me how to search with Item(s) Data or if SLIMS can not do that for now, can you note this idea to the next version of SLIMS??? Thank you guys very much!!!

![Screenshot_1](https://user-images.githubusercontent.com/9654732/124576670-bc348d80-de76-11eb-85b5-8748d8ec270a.png)

Best Regards,
Jing

**Comment by heroesoebekti** [comment]
you can find the book by item data on menu item list

**Comment by liwenjing93** [comment]
> you can find the book by item data on menu item list

Wow, I did not know that. Thank you so much!!!
